<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_1590717403697</name>
   <tag></tag>
   <elementGuidId>c6fcd2a2-3a37-409e-ab4d-4964131a9867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ng-app&quot;]/app-root/app-page-outlet/app-page-rewardmanagement/div/main/div/div/div/div[6]/div/div/div/div[3]/div/div/ul/li[2]/div/div/div/div[3]/div/div/div[1]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1590717403697</value>
   </webElementProperties>
</WebElementEntity>
